onboarding = false
[keys]
prefix = "ctrl+space"
settings = ""
detach = "prefix+d"
zoom = "prefix+i"
next_agent = "alt+j"
previous_agent = "alt+k"
previous_workspace = "alt+h"
next_workspace = "alt+l"
split_vertical = "prefix+v"
split_horizontal = "prefix+s"

[[keys.command]]
key = "ctrl+h"
type = "shell"
command = "~/.config/herdr/navigator.sh left ctrl+h"

[[keys.command]]
key = "ctrl+j"
type = "shell"
command = "~/.config/herdr/navigator.sh down ctrl+j"

[[keys.command]]
key = "ctrl+k"
type = "shell"
command = "~/.config/herdr/navigator.sh up ctrl+k"

[[keys.command]]
key = "ctrl+l"
type = "shell"
command = "~/.config/herdr/navigator.sh right ctrl+l"

[ui]
show_agent_labels_on_pane_borders = true
