local hyperKey = require('hyperKey')
hyperKey:bind({}, "A", function() hs.application.launchOrFocus("Atom") end, nil)
hyperKey:bind({}, "C", function() hs.application.launchOrFocus("Google Chrome") end, nil)
hyperKey:bind({}, "D", function() hs.application.launchOrFocus("大象") end, nil)
hyperKey:bind({}, "E", function() hs.application.launchOrFocus("Evernote") end, nil)
hyperKey:bind({}, "i", function() hs.application.launchOrFocus("iTerm") end, nil)
hyperKey:bind({}, "L", function() hs.application.launchOrFocus("Lantern") end, nil)
hyperKey:bind({}, "M", function() hs.application.launchOrFocus("Airmail 3") end, nil)
hyperKey:bind({}, "P", function() hs.application.launchOrFocus("Adobe Photoshop CC 2015") end, nil)
hyperKey:bind({}, "Q", function() hs.application.launchOrFocus("QQ") end, nil)
hyperKey:bind({}, "S", function() hs.application.launchOrFocus("SourceTree") end, nil)
hyperKey:bind({}, "T", function() hs.application.launchOrFocus("Thunder") end, nil)
hyperKey:bind({}, "V", function() hs.application.launchOrFocus("Visual Studio Code") end, nil)

hyperKey:bind({}, "H", function() hs.application.launchOrFocus("Charles") end, nil)
hyperKey:bind({}, "P", function() hs.application.launchOrFocus("Dash") end, nil)
